<?php

return [
    'call_create_path'      => '/call/create',
    'worker_create_path'      => '/worker/create',
    'call_modify_path'      => '/call/modify',
    'channel_register_path' => '/sip_user/register',
    'channel_unregister_path' => '/sip_user/unregister',
    'websocket_send_path' => '/websocket/send',
    'set_license'          => '/license',
    'date_time_format' => 'd-m-Y H:i:s',
    'AGI_HOST' => '127.0.0.1:6785',
    // 'core_functions' =>[
    //     ['name' => 'SIPCALL', 'func_type' => 1, 'func' => 'sip_call'],
    //     ['name' => 'EXTENSION', 'func_type' => 0, 'func' => 'extension'],
    //     ['name' => 'SMS', 'func_type' => 0, 'func' => 'sms'],
    //     ['name' => 'ANNOUNCEMENT', 'func_type' => 0, 'func' => 'announcement'],
    //     ['name' => 'OUTBOUND ROUTE', 'func_type' => 1, 'func' => 'outbound_route'],
    //     ['name' => 'IVR', 'func_type' => 0, 'func' => 'ivr'],
    //     ['name' => 'CUSTOM FUNCTION', 'func_type' => 0, 'func' => 'custom_function'],
    //     ['name' => 'TERMINATE CALL', 'func_type' => 0, 'func' => 'terminate_call'],
    //     ['name' => 'VOICE RECORD', 'func_type' => 0, 'func' => 'voice_record'],
    //     ['name' => 'RING GROUP', 'func_type' => 0, 'func' => 'ring_group'],
    //     ['name' => 'CALL QUEUE', 'func_type' => 0, 'func' => 'call_queue'],
    //     ['name' => 'SHORT CODE', 'func_type' => 1, 'func' => 'short_code'],
    //     ['name' => 'TIME CONDITION', 'func_type' => 0, 'func' => 'time_condition'],
    //     ['name' => 'CALL SURVEY', 'func_type' => 0, 'func' => 'call_survey'],
    //     ['name' => 'CALL PARKING', 'func_type' => 0, 'func' => 'call_parking'],
    //     ['name' => 'QUEUE JOIN', 'func_type' => 1, 'func' => 'queue_join'],
    //     ['name' => 'AI ASSISTANT', 'func_type' => 1, 'func' => 'ai_assistant'],
    //     ['name' => 'STREAM', 'func_type' => 0, 'func' => 'stream'],
    // ],
    'core_functions' => [
        ['name' => 'SIPCALL', 'func_type' => 1, 'func' => 'sip_call', 'id' => 1],
        ['name' => 'EXTENSION', 'func_type' => 0, 'func' => 'extension', 'id' => 2],
        ['name' => 'SMS', 'func_type' => 0, 'func' => 'sms', 'id' => 3],
        ['name' => 'ANNOUNCEMENT', 'func_type' => 0, 'func' => 'announcement', 'id' => 4],
        ['name' => 'OUTBOUND ROUTE', 'func_type' => 1, 'func' => 'outbound_route', 'id' => 5],
        ['name' => 'IVR', 'func_type' => 0, 'func' => 'ivr', 'id' => 6],
        ['name' => 'CUSTOM FUNCTION', 'func_type' => 0, 'func' => 'custom_function', 'id' => 7],
        ['name' => 'TERMINATE CALL', 'func_type' => 0, 'func' => 'terminate_call', 'id' => 8],
        ['name' => 'VOICE RECORD', 'func_type' => 0, 'func' => 'voice_record', 'id' => 9],
        ['name' => 'RING GROUP', 'func_type' => 0, 'func' => 'ring_group', 'id' => 10],
        ['name' => 'CALL QUEUE', 'func_type' => 0, 'func' => 'call_queue', 'id' => 11],
        ['name' => 'SHORT CODE', 'func_type' => 1, 'func' => 'short_code', 'id' => 12],
        ['name' => 'TIME CONDITION', 'func_type' => 0, 'func' => 'time_condition', 'id' => 13],
        ['name' => 'CALL SURVEY', 'func_type' => 0, 'func' => 'call_survey', 'id' => 14],
        ['name' => 'CALL PARKING', 'func_type' => 0, 'func' => 'call_parking', 'id' => 15],
        ['name' => 'QUEUE JOIN', 'func_type' => 1, 'func' => 'queue_join', 'id' => 16],
        ['name' => 'AI ASSISTANT', 'func_type' => 1, 'func' => 'ai_assistant', 'id' => 17],
        ['name' => 'STREAM', 'func_type' => 0, 'func' => 'stream', 'id' => 18],
    ],

    'short_codes' => [
        'always_forward_activate' => '*22',
        'forward_when_busy' => '*23',
        // 'forward_when_no_answer' =>'*24',
        'forward_when_unavailable' => '*25',
        'forward_deativate' => '*26',
        'forward_set' => '*27', // *27*01xxxx#
        'enable_disabled_dynamic_queue' => '*28', // *28*3030*1# queue code - 3030 , 1 - active
    ],
];
